### ISSUE TITLE
关于FedRS

### ISSUE THREAD

**Issue by Bhongcheng** [lxcnju/FedRepo#7]
我想请教一个问题
![image](https://user-images.githubusercontent.com/90205287/219946260-ea4c6215-192d-4fd7-949f-3990c11fcce6.png)
这样做是不是忽略了分类器的Bias参数呀？有什么玄机吗？

**Comment by Bhongcheng** [comment]
上一个问题我理解为最后一层的bias不会改变也无所谓。我又有一个新的问题想请教：论文里所描述的是看得到的类别alpha为1，您在代码里的cdist实现是不是并不满足呀

**Comment by knight-fzq** [comment]
I have similar questions about this. Here i think it's a kind of tech like logit adjustment on labels among clients instead of the meaning introduced in the paper. I think the author should explain these codes or it is hard for us to follow and reproduce.

**Comment by knight-fzq** [comment]
> 我想请教一个问题 ![image](https://user-images.githubusercontent.com/90205287/219946260-ea4c6215-192d-4fd7-949f-3990c11fcce6.png) 这样做是不是忽略了分类器的Bias参数呀？有什么玄机吗？

In fedaws and fedrs(paper), they both didn't use Bias. They use the result(feature*weight) to denote the distance(similarity or scores) to each category.

**Comment by Bhongcheng** [comment]
> > 我想请教一个问题 ![image](https://user-images.githubusercontent.com/90205287/219946260-ea4c6215-192d-4fd7-949f-3990c11fcce6.png) 这样做是不是忽略了分类器的Bias参数呀？有什么玄机吗？
> 
> In fedaws and fedrs(paper), they both didn't use Bias. They use the result(feature*weight) to denote the distance(similarity or scores) to each category.

Thanks for your help!

**Comment by lxcnju** [comment]
澄清解释一下：FedRS原文解决的是类别缺失场景，构造实验里面不缺失的类别数量基本上均衡的（split_by_label)的划分方式，比如某个客户端拥有3个类别，这3个类别数目都有100个样本，此时cdist满足见得到的类别为1，见不到的为0。但split_by_dirichlet也是一种场景的实验数据集划分方法，也更为常用，此时缺失类别的alpha依然为0，最多数类别alpha为1，其余见得到的类别但是数目相对较少的采用较小的alpha。该代码实现综合考虑了这两种场景。fedrs出发点和logit adjustment方法不一致，虽然看起来形式差不多。
